# Generated by Django 5.1.6 on 2025-03-12 07:36

from django.db import migrations, models
default_app_config = 'bstation.apps.BstationConfig'

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DanmakuData",
            fields=[
                ("danmaku_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bvid", models.CharField(max_length=12, verbose_name="视频唯一标识")),
                ("content", models.CharField(max_length=150, verbose_name="弹幕内容")),
                (
                    "send_time",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="发送时间(秒)"
                    ),
                ),
                (
                    "sentiment",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="情感倾向(-1/0/1)"
                    ),
                ),
                (
                    "cluster_id",
                    models.IntegerField(blank=True, null=True, verbose_name="文本聚类分组"),
                ),
            ],
            options={
                "verbose_name": "弹幕数据",
                "verbose_name_plural": "弹幕数据",
            },
        ),
        migrations.CreateModel(
            name="HourlyStats",
            fields=[
                (
                    "stat_time",
                    models.DateTimeField(
                        primary_key=True, serialize=False, verbose_name="统计时间"
                    ),
                ),
                (
                    "total_views",
                    models.PositiveBigIntegerField(default=0, verbose_name="总播放量"),
                ),
                (
                    "new_videos",
                    models.PositiveIntegerField(default=0, verbose_name="新增视频数"),
                ),
                (
                    "active_users",
                    models.PositiveIntegerField(default=0, verbose_name="活跃用户数"),
                ),
                (
                    "category_dist",
                    models.JSONField(blank=True, null=True, verbose_name="分区流量分布"),
                ),
            ],
            options={
                "verbose_name": "小时级统计",
                "verbose_name_plural": "小时级统计",
            },
        ),
        migrations.CreateModel(
            name="RecommendLog",
            fields=[
                ("rec_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_mid", models.CharField(max_length=20, verbose_name="用户MID")),
                (
                    "recommend_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="推荐类型"
                    ),
                ),
                ("video_list", models.JSONField(verbose_name="推荐视频列表")),
                (
                    "rec_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="推荐时间"),
                ),
            ],
            options={
                "verbose_name": "推荐日志",
                "verbose_name_plural": "推荐日志",
            },
        ),
        migrations.CreateModel(
            name="UpCreator",
            fields=[
                (
                    "author_mid",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UP主MID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="UP主名称")),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="等级"
                    ),
                ),
                (
                    "fans_count",
                    models.PositiveIntegerField(default=0, verbose_name="粉丝数"),
                ),
                (
                    "total_views",
                    models.PositiveBigIntegerField(default=0, verbose_name="总播放量"),
                ),
                (
                    "avg_like_rate",
                    models.FloatField(blank=True, null=True, verbose_name="平均点赞率"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后数据更新时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "UP主信息",
                "verbose_name_plural": "UP主信息",
            },
        ),
        migrations.CreateModel(
            name="UserBehavior",
            fields=[
                ("log_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_mid", models.CharField(max_length=20, verbose_name="用户MID")),
                ("bvid", models.CharField(max_length=12, verbose_name="视频唯一标识")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view", "观看"),
                            ("like", "点赞"),
                            ("coin", "投币"),
                            ("collect", "收藏"),
                            ("share", "分享"),
                            ("search", "搜索"),
                        ],
                        max_length=20,
                        verbose_name="行为类型",
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="行为时间"),
                ),
                (
                    "duration",
                    models.IntegerField(blank=True, null=True, verbose_name="观看时长(秒)"),
                ),
                (
                    "search_keyword",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="搜索关键词"
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="设备信息"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户行为日志",
                "verbose_name_plural": "用户行为日志",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bv_number", models.CharField(max_length=20, verbose_name="BV号")),
                ("title", models.CharField(max_length=200, verbose_name="视频标题")),
                ("up_mid", models.CharField(max_length=20, verbose_name="UP主MID")),
                ("publish_time", models.DateTimeField(verbose_name="发布时间")),
            ],
            options={
                "verbose_name": "视频信息",
                "verbose_name_plural": "视频信息",
            },
        ),
        migrations.CreateModel(
            name="VideoBasic",
            fields=[
                (
                    "bvid",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="视频唯一标识",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="视频标题")),
                ("author_mid", models.CharField(max_length=20, verbose_name="UP主MID")),
                ("pub_time", models.DateTimeField(verbose_name="发布时间")),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="视频时长(秒)"
                    ),
                ),
                (
                    "category_id",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="分区ID"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, null=True, verbose_name="视频标签(JSON数组)"
                    ),
                ),
                ("description", models.TextField(verbose_name="视频简介")),
                (
                    "keywords",
                    models.JSONField(blank=True, null=True, verbose_name="标题关键词分析结果"),
                ),
            ],
            options={
                "verbose_name": "视频基本信息",
                "verbose_name_plural": "视频基本信息",
            },
        ),
        migrations.CreateModel(
            name="VideoCategory",
            fields=[
                (
                    "category_id",
                    models.SmallIntegerField(
                        primary_key=True, serialize=False, verbose_name="分区ID"
                    ),
                ),
                ("category_name", models.CharField(max_length=30, verbose_name="分区名称")),
                (
                    "parent_id",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="父分区ID"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="业务分类"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频分类",
                "verbose_name_plural": "视频分类",
            },
        ),
        migrations.CreateModel(
            name="VideoComment",
            fields=[
                (
                    "rpid",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="评论ID"
                    ),
                ),
                ("bvid", models.CharField(max_length=12, verbose_name="视频唯一标识")),
                (
                    "user_mid",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="用户MID"
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "like_num",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "sentiment_score",
                    models.FloatField(blank=True, null=True, verbose_name="情感分析得分"),
                ),
                (
                    "topic_class",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="话题分类"
                    ),
                ),
            ],
            options={
                "verbose_name": "视频评论",
                "verbose_name_plural": "视频评论",
            },
        ),
        migrations.CreateModel(
            name="VideoStats",
            fields=[
                ("stat_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("bvid", models.CharField(max_length=12, verbose_name="视频唯一标识")),
                (
                    "collect_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="采集时间"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="播放量"),
                ),
                (
                    "danmaku_count",
                    models.PositiveIntegerField(default=0, verbose_name="弹幕数"),
                ),
                (
                    "reply_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "favorite_count",
                    models.PositiveIntegerField(default=0, verbose_name="收藏量"),
                ),
                (
                    "coin_count",
                    models.PositiveIntegerField(default=0, verbose_name="投币数"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
            ],
            options={
                "verbose_name": "视频动态指标",
                "verbose_name_plural": "视频动态指标",
                "indexes": [
                    models.Index(fields=["collect_time"], name="idx_collect_time")
                ],
            },
        ),
    ]
